export {default as About} from './About/About';
export {default as Footer} from './Footer/Footer';
export {default as Header} from './Header/Header';
export {default as Skills} from './Skills/Skills';
// export {default as Testimonial} from './Testimonial/Testimonial';
export {default as Certificates} from './Certificates/Certificates';
export {default as Work} from './Work/Work';
export {default as Designs} from './Designs/Designs';
export {default as Education} from './Education/Education';
export {default as Roles} from './Roles/Roles';
export {default as Achievements} from './Achievements/Achievements';